import type { AuditLogEntry } from "@/lib/audit-types";
import { shiftContext } from "@/lib/mock-data";

/** Permission-scoped audit log for the signed-in nurse's shift view. */
export const auditLog: AuditLogEntry[] = [
  {
    id: "audit-001",
    kind: "case_note_added",
    summary: "Added follow-up note on James Okonkwo's active case",
    actorName: shiftContext.nurseName,
    actorRole: "RN",
    occurredMinutesAgo: 3,
    patientId: "PT-2841",
    patientName: "James Okonkwo",
    ward: "4B",
    bed: "12",
    caseId: "case-001",
    details: [
      { label: "Case", value: "case-001 · Respiratory distress" },
      { label: "Patient", value: "James Okonkwo · Ward 4B · Bed 12" },
      {
        label: "Note",
        value: "Family at bedside — kept briefed. Awaiting backup doctor response.",
      },
      { label: "Recorded by", value: `${shiftContext.nurseName} · RN` },
    ],
  },
  {
    id: "audit-002",
    kind: "case_escalated",
    summary: "Case escalated — Dr. Patel timed out on James Okonkwo",
    actorName: "RoundSync",
    actorRole: "System",
    occurredMinutesAgo: 2,
    patientId: "PT-2841",
    patientName: "James Okonkwo",
    ward: "4B",
    bed: "12",
    caseId: "case-001",
    details: [
      { label: "Case", value: "case-001 · Critical" },
      { label: "From", value: "Dr. Patel · On-call" },
      { label: "To", value: "Dr. Adeyemi · Backup on-call" },
      { label: "Reason", value: "No response within timeout window" },
      { label: "Triggered by", value: `${shiftContext.nurseName} · RN` },
    ],
  },
  {
    id: "audit-003",
    kind: "case_note_added",
    summary: "Added follow-up note on Emmanuel Adeyemi's reopened case",
    actorName: shiftContext.nurseName,
    actorRole: "RN",
    occurredMinutesAgo: 1,
    patientId: "PT-2756",
    patientName: "Emmanuel Adeyemi",
    ward: "4B",
    bed: "03",
    caseId: "case-003",
    details: [
      { label: "Case", value: "case-003 · BP spike returned" },
      { label: "Patient", value: "Emmanuel Adeyemi · Ward 4B · Bed 03" },
      {
        label: "Note",
        value: "Vitals stabilizing after earlier spike — still monitoring closely.",
      },
      { label: "Recorded by", value: `${shiftContext.nurseName} · RN` },
    ],
  },
  {
    id: "audit-004",
    kind: "alert_acknowledged",
    summary: "Dr. Patel acknowledged alert on Emmanuel Adeyemi's case",
    actorName: "Dr. Patel",
    actorRole: "On-call",
    occurredMinutesAgo: 1,
    patientId: "PT-2756",
    patientName: "Emmanuel Adeyemi",
    ward: "4B",
    bed: "03",
    caseId: "case-003",
    details: [
      { label: "Case", value: "case-003 · Urgent" },
      { label: "Alert recipient", value: "Dr. Patel · On-call" },
      { label: "Response", value: "Acknowledged" },
      { label: "Triggered by", value: `${shiftContext.nurseName} · RN` },
    ],
  },
  {
    id: "audit-005",
    kind: "case_triggered",
    summary: "Triggered emergency case for Emmanuel Adeyemi — BP spike returned",
    actorName: shiftContext.nurseName,
    actorRole: "RN",
    occurredMinutesAgo: 3,
    patientId: "PT-2756",
    patientName: "Emmanuel Adeyemi",
    ward: "4B",
    bed: "03",
    caseId: "case-003",
    details: [
      { label: "Case", value: "case-003 · Urgent · Reopened" },
      { label: "Patient", value: "Emmanuel Adeyemi · Ward 4B · Bed 03" },
      {
        label: "Trigger note",
        value: "BP 168/102 on recheck after brief improvement. Patient symptomatic with headache.",
      },
      { label: "Urgency", value: "Urgent" },
    ],
  },
  {
    id: "audit-006",
    kind: "case_triggered",
    summary: "Triggered emergency case for James Okonkwo — respiratory distress",
    actorName: shiftContext.nurseName,
    actorRole: "RN",
    occurredMinutesAgo: 6,
    patientId: "PT-2841",
    patientName: "James Okonkwo",
    ward: "4B",
    bed: "12",
    caseId: "case-001",
    details: [
      { label: "Case", value: "case-001 · Critical" },
      { label: "Patient", value: "James Okonkwo · Ward 4B · Bed 12" },
      {
        label: "Trigger note",
        value:
          "SpO₂ dropped to 88%, patient visibly distressed. Started supplemental O₂ and rechecked vitals.",
      },
      { label: "Urgency", value: "Critical" },
    ],
  },
  {
    id: "audit-007",
    kind: "alert_acknowledged",
    summary: "Pharmacy acknowledged alert on Fatima Bello's case",
    actorName: "Pharmacy",
    actorRole: "Pharmacy",
    occurredMinutesAgo: 11,
    patientId: "PT-2903",
    patientName: "Fatima Bello",
    ward: "4B",
    bed: "08",
    caseId: "case-002",
    details: [
      { label: "Case", value: "case-002 · Moderate" },
      { label: "Alert recipient", value: "Pharmacy" },
      { label: "Response", value: "Acknowledged" },
      { label: "Triggered by", value: `${shiftContext.nurseName} · RN` },
    ],
  },
  {
    id: "audit-008",
    kind: "case_triggered",
    summary: "Triggered emergency case for Fatima Bello — medication query",
    actorName: shiftContext.nurseName,
    actorRole: "RN",
    occurredMinutesAgo: 22,
    patientId: "PT-2903",
    patientName: "Fatima Bello",
    ward: "4B",
    bed: "08",
    caseId: "case-002",
    details: [
      { label: "Case", value: "case-002 · Moderate" },
      { label: "Patient", value: "Fatima Bello · Ward 4B · Bed 08" },
      {
        label: "Trigger note",
        value:
          "Patient reported dizziness after morning meds. Need pharmacy review before next Metformin dose.",
      },
      { label: "Urgency", value: "Moderate" },
    ],
  },
  {
    id: "audit-009",
    kind: "task_completed",
    summary: "Completed vitals check for Emmanuel Adeyemi",
    actorName: shiftContext.nurseName,
    actorRole: "RN",
    occurredMinutesAgo: 42,
    patientId: "PT-2756",
    patientName: "Emmanuel Adeyemi",
    ward: "4B",
    bed: "03",
    taskId: "task-009",
    details: [
      { label: "Task", value: "Vitals check" },
      { label: "Patient", value: "Emmanuel Adeyemi · Ward 4B · Bed 03" },
      { label: "Task ID", value: "task-009" },
      { label: "Completed by", value: `${shiftContext.nurseName} · RN` },
    ],
  },
  {
    id: "audit-010",
    kind: "case_resolved",
    summary: "Amina Yusuf's case marked resolved by Dr. Patel",
    actorName: "Dr. Patel",
    actorRole: "On-call",
    occurredMinutesAgo: 45,
    patientId: "PT-2944",
    patientName: "Amina Yusuf",
    ward: "4B",
    bed: "11",
    caseId: "case-004",
    details: [
      { label: "Case", value: "case-004 · Moderate" },
      { label: "Patient", value: "Amina Yusuf · Ward 4B · Bed 11" },
      { label: "Resolution", value: "Temperature elevation — resolved after review" },
      {
        label: "Closing note",
        value: "Reviewed cultures — continue monitoring. Case can close from clinical side.",
      },
      { label: "Triggered by", value: `${shiftContext.nurseName} · RN` },
    ],
  },
  {
    id: "audit-011",
    kind: "task_completed",
    summary: "Completed medication round for Chidi Nwosu",
    actorName: shiftContext.nurseName,
    actorRole: "RN",
    occurredMinutesAgo: 68,
    patientId: "PT-2688",
    patientName: "Chidi Nwosu",
    ward: "4B",
    bed: "06",
    taskId: "task-insulin-historical",
    details: [
      { label: "Task", value: "Medication — Insulin" },
      { label: "Patient", value: "Chidi Nwosu · Ward 4B · Bed 06" },
      { label: "Completed by", value: `${shiftContext.nurseName} · RN` },
    ],
  },
  {
    id: "audit-012",
    kind: "case_triggered",
    summary: "Triggered emergency case for Amina Yusuf — temperature elevation",
    actorName: shiftContext.nurseName,
    actorRole: "RN",
    occurredMinutesAgo: 240,
    patientId: "PT-2944",
    patientName: "Amina Yusuf",
    ward: "4B",
    bed: "11",
    caseId: "case-004",
    details: [
      { label: "Case", value: "case-004 · Moderate · Resolved" },
      { label: "Patient", value: "Amina Yusuf · Ward 4B · Bed 11" },
      {
        label: "Trigger note",
        value: "Temp 38.2°C with rigors. Blood cultures drawn, fluids started.",
      },
      { label: "Urgency", value: "Moderate" },
    ],
  },
];
